development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username: vsinfo
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: vsinfo
  password:
  
production: 
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username: vsinfo
  password:
  port: 5432

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
