development:
  adapter: postgresql
  encoding: unicode
  database: project_development
  pool: 5
  username: vsinfo
  password:

test: &TEST
  adapter: postgresql
  encoding: unicode
  database: project_test
  pool: 5
  username: vsinfo
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: project_production
  pool: 5
  username: vsinfo
  password:
