airplane=Airplane.create( reg: "G-VEIL", ac_type: "A346", name: "Queen Of The Skies", j_capacity: 45, w_capacity:38, y_capacity: 225, ife: "Matsushita 3000 'V:port'", new_livery: false)
airplane=Airplane.create( reg: "G-VSSH", ac_type: "A346", name: "Sweet Dreamer", j_capacity: 45, w_capacity:38, y_capacity: 225, ife: "Matsushita 3000 'V:port'", new_livery: false)
airplane=Airplane.create( reg: "G-VNAP", ac_type: "A346", name: "Sleeping Beauty", j_capacity: 45, w_capacity:38, y_capacity: 225, ife: "Matsushita 3000 'V:port'", new_livery: false)
airplane=Airplane.create( reg: "G-VGAS", ac_type: "A346", name: "Varga Girl", j_capacity: 45, w_capacity:38, y_capacity: 225, ife: "Matsushita 3000 'V:port'", new_livery: false)
airplane=Airplane.create( reg: "G-VWKD", ac_type: "A346", name: "Miss Behavin'", j_capacity: 45, w_capacity:38, y_capacity: 225, ife: "Matsushita 3000 'V:port'", new_livery: false)
airplane=Airplane.create( reg: "G-VBLU", ac_type: "A346", name: "Soul Sister", j_capacity: 45, w_capacity:38, y_capacity: 225, ife: "Matsushita 3000 'V:port'", new_livery: false)
airplane=Airplane.create( reg: "G-VWIN", ac_type: "A346", name: "Lady Luck", j_capacity: 45, w_capacity:38, y_capacity: 225, ife: "Matsushita 3000 'V:port'", new_livery: false)
airplane=Airplane.create( reg: "G-VFIT", ac_type: "A346", name: "Dancing Queen", j_capacity: 45, w_capacity:38, y_capacity: 225, ife: "Matsushita 3000 'V:port'", new_livery: false)
airplane=Airplane.create( reg: "G-VFIZ", ac_type: "A346", name: "Bubbles", j_capacity: 45, w_capacity:38, y_capacity: 225, ife: "Matsushita 3000 'V:port'", new_livery: false)
airplane=Airplane.create( reg: "G-VYOU", ac_type: "A346", name: "Emmeline Heaney", j_capacity: 45, w_capacity:38, y_capacity: 225, ife: "Matsushita 3000 'V:port'", new_livery: false)
airplane=Airplane.create( reg: "G-VRED", ac_type: "A346", name: "Scarlet Lady", j_capacity: 45, w_capacity:38, y_capacity: 225, ife: "Matsushita 3000 'V:port'", new_livery: false)
airplane=Airplane.create( reg: "G-VWEB", ac_type: "A346", name: "Surfer Girl", j_capacity: 45, w_capacity:38, y_capacity: 225, ife: "Matsushita 3000 'V:port'", new_livery: false)
airplane=Airplane.create( reg: "G-VBUG", ac_type: "A346", name: "Lady Bird", j_capacity: 45, w_capacity:38, y_capacity: 225, ife: "Matsushita 3000 'V:port'", new_livery: false)
airplane=Airplane.create( reg: "G-VSUN", ac_type: "A343", name: "Rainbow Lady", j_capacity: 34, w_capacity:35, y_capacity: 171, ife: "Matsushita 3000 'V:port'", new_livery: false)
airplane=Airplane.create( reg: "G-VELD", ac_type: "A343", name: "African Queen", j_capacity: 34, w_capacity:35, y_capacity: 171, ife: "Matsushita 2000E 'Odyssey'", new_livery: true)
airplane=Airplane.create( reg: "G-VSXY", ac_type: "A333", name: "Beauty Queen", j_capacity: 33, w_capacity:48, y_capacity: 185, ife: "Panasonic eX2", new_livery: true)
airplane=Airplane.create( reg: "G-VKSS", ac_type: "A333", name: "Mademoiselle Rouge", j_capacity: 33, w_capacity:48, y_capacity: 185, ife: "Panasonic eX2", new_livery: true)
airplane=Airplane.create( reg: "G-VLUV", ac_type: "A333", name: "Lady Love", j_capacity: 33, w_capacity:48, y_capacity: 185, ife: "Panasonic eX2", new_livery: true)
airplane=Airplane.create( reg: "G-VGEM", ac_type: "A333", name: "Diamond Girl", j_capacity: 33, w_capacity:48, y_capacity: 185, ife: "Panasonic eX2", new_livery: true)
airplane=Airplane.create( reg: "G-VINE", ac_type: "A333", name: "Champagne Belle", j_capacity: 33, w_capacity:48, y_capacity: 185, ife: "Panasonic eX2", new_livery: true)
airplane=Airplane.create( reg: "G-VRAY", ac_type: "A333", name: "Miss Sunshine", j_capacity: 33, w_capacity:48, y_capacity: 185, ife: "Panasonic eX2", new_livery: true)
airplane=Airplane.create( reg: "G-VNYC", ac_type: "A333", name: "Uptown Girl", j_capacity: 33, w_capacity:48, y_capacity: 185, ife: "Panasonic eX2", new_livery: true)
airplane=Airplane.create( reg: "G-VGBR", ac_type: "A333", name: "Golden Girl", j_capacity: 33, w_capacity:48, y_capacity: 185, ife: "Panasonic eX2", new_livery: true)
airplane=Airplane.create( reg: "G-VWAG", ac_type: "A333", name: "Miss England", j_capacity: 33, w_capacity:48, y_capacity: 185, ife: "Panasonic eX2", new_livery: true)
airplane=Airplane.create( reg: "G-VUFO", ac_type: "A333", name: "Lady Stardust", j_capacity: 33, w_capacity:48, y_capacity: 185, ife: "Panasonic eX2", new_livery: true)
airplane=Airplane.create( reg: "G-VFAB", ac_type: "B744", name: "Lady Penelope", j_capacity: 44, w_capacity:62, y_capacity: 261, ife: "Matsushita 3000 'V:port'", new_livery: false)
airplane=Airplane.create( reg: "G-VHOT", ac_type: "B744", name: "Tubular Belle", j_capacity: 44, w_capacity:62, y_capacity: 261, ife: "Matsushita 3000 'V:port'", new_livery: false)
airplane=Airplane.create( reg: "G-VBIG", ac_type: "B744", name: "Tinker Bell", j_capacity: 44, w_capacity:62, y_capacity: 261, ife: "Matsushita 3000 'V:port'", new_livery: true)
airplane=Airplane.create( reg: "G-VAST", ac_type: "B744", name: "Ladybird", j_capacity: 14, w_capacity:66, y_capacity: 375, ife: "Panasonic eX2", new_livery: true)
airplane=Airplane.create( reg: "G-VXLG", ac_type: "B744", name: "Ruby Tuesday", j_capacity: 14, w_capacity:66, y_capacity: 375, ife: "Panasonic eX2", new_livery: true)
airplane=Airplane.create( reg: "G-VROS", ac_type: "B744", name: "English Rose", j_capacity: 14, w_capacity:66, y_capacity: 375, ife: "Panasonic eX2", new_livery: false)
airplane=Airplane.create( reg: "G-VGAL", ac_type: "B744", name: "Jersey Girl", j_capacity: 14, w_capacity:66, y_capacity: 375, ife: "Panasonic eX2", new_livery: false)
airplane=Airplane.create( reg: "G-VLIP", ac_type: "B744", name: "Hot Lips", j_capacity: 14, w_capacity:66, y_capacity: 375, ife: "Panasonic eX2", new_livery: false)
airplane=Airplane.create( reg: "G-VROM", ac_type: "B744", name: "Barbarella", j_capacity: 14, w_capacity:66, y_capacity: 375, ife: "Panasonic eX2", new_livery: true)
airplane=Airplane.create( reg: "G-VROY", ac_type: "B744", name: "Pretty Woman", j_capacity: 14, w_capacity:66, y_capacity: 375, ife: "Panasonic eX2", new_livery: false)
airplane=Airplane.create( reg: "G-VWOW", ac_type: "B744", name: "Cosmic Girl", j_capacity: 44, w_capacity:62, y_capacity: 261, ife: "Matsushita 3000 'V:port'", new_livery: false)
airplane=Airplane.create( reg: "G-VROC", ac_type: "B744", name: "Mustang Sally", j_capacity: 44, w_capacity:62, y_capacity: 261, ife: "Matsushita 3000 'V:port'", new_livery: true)
airplane=Airplane.create( reg: "G-VNEW", ac_type: "B789", name: "Birthday Girl", j_capacity: 31, w_capacity:35, y_capacity: 198, ife: "Panasonic eX3", new_livery: true)

Airport.create(code: "ANU", name: "Antigua", city: "Antigua", country: "Antigua and Barbuda", latlon: "17.137,-61.793", timezone: "America/Antigua")
Airport.create(code: "ATL", name: "Atlanta", city: "Atlanta", country: "United States", latlon: "33.637,-84.428", timezone: "America/New_York")
Airport.create(code: "BFS", name: "Belfast", city: "Belfast", country: "United Kingdom", latlon: "54.658,-6.216", timezone: "Europe/London")
Airport.create(code: "BGI", name: "Barbados", city: "Bridgetown", country: "Barbados", latlon: "13.075,-59.492", timezone: "America/Barbados")
Airport.create(code: "BOS", name: "Boston", city: "Boston", country: "United States", latlon: "42.364,-71.005", timezone: "America/New_York")
Airport.create(code: "CPT", name: "Cape Town", city: "Cape Town", country: "South Africa", latlon: "-33.965,18.602", timezone: "Africa/Johannesburg")
Airport.create(code: "CUN", name: "Cancun", city: "Cancun", country: "Mexico", latlon: "21.037,-86.877", timezone: "America/Mexico_City")
Airport.create(code: "DEL", name: "Delhi", city: "Delhi", country: "India", latlon: "28.567,77.103", timezone: "Asia/Calcutta")
Airport.create(code: "DTW", name: "Detroit", city: "Detroit", country: "United States", latlon: "42.212,-83.353", timezone: "America/New_York")
Airport.create(code: "DXB", name: "Dubai", city: "Dubai", country: "United Arab Emirates", latlon: "25.253,55.364", timezone: "Asia/Dubai")
Airport.create(code: "EWR", name: "Newark", city: "Newark", country: "United States", latlon: "40.693,-74.169", timezone: "America/New_York")
Airport.create(code: "GLA", name: "Glasgow", city: "Glasgow", country: "United Kingdom", latlon: "55.872,-4.433", timezone: "Europe/London")
Airport.create(code: "GND", name: "Grenada", city: "Point Salines", country: "Grenada", latlon: "12.004,-61.786", timezone: "America/Grenada")
Airport.create(code: "HAV", name: "Havana", city: "Havana", country: "Cuba", latlon: "22.989,-82.409", timezone: "America/Havana")
Airport.create(code: "HKG", name: "Hong Kong", city: "Hong Kong", country: "Hong Kong", latlon: "22.309,113.915", timezone: "Asia/Hong_Kong")
Airport.create(code: "IAD", name: "Washington Dulles", city: "Washington", country: "United States", latlon: "38.945,-77.456", timezone: "America/New_York")
Airport.create(code: "JFK", name: "New York - JFK", city: "New York", country: "United States", latlon: "40.64,-73.779", timezone: "America/New_York")
Airport.create(code: "JNB", name: "Johannesburg", city: "Johannesburg", country: "South Africa", latlon: "-26.139,28.246", timezone: "Africa/Johannesburg")
Airport.create(code: "LAS", name: "Las Vegas", city: "Las Vegas", country: "United States", latlon: "36.08,-115.152", timezone: "America/Los_Angeles")
Airport.create(code: "LAX", name: "Los Angeles", city: "Los Angeles", country: "United States", latlon: "33.943,-118.408", timezone: "America/Los_Angeles")
Airport.create(code: "LGW", name: "London - Gatwick", city: "London", country: "United Kingdom", latlon: "51.148,-0.19", timezone: "Europe/London")
Airport.create(code: "LHR", name: "London - Heathrow", city: "London", country: "United Kingdom", latlon: "51.478,-0.461", timezone: "Europe/London")
Airport.create(code: "LOS", name: "Lagos", city: "Lagos", country: "Nigeria", latlon: "6.577,3.321", timezone: "Africa/Lagos")
Airport.create(code: "MAN", name: "Manchester", city: "Manchester", country: "United Kingdom", latlon: "53.354,-2.275", timezone: "Europe/London")
Airport.create(code: "MBJ", name: "Montego Bay", city: "Montego Bay", country: "Jamaica", latlon: "18.504,-77.913", timezone: "America/Jamaica")
Airport.create(code: "MCO", name: "Orlando", city: "Orlando", country: "United States", latlon: "28.429,-81.309", timezone: "America/New_York")
Airport.create(code: "MIA", name: "Miami", city: "Miami", country: "United States", latlon: "25.793,-80.291", timezone: "America/New_York")
Airport.create(code: "ORD", name: "Chicago - O'Hare", city: "Chicago", country: "United States", latlon: "41.979,-87.905", timezone: "America/Chicago")
Airport.create(code: "PVG", name: "Shanghai", city: "Shanghai", country: "China", latlon: "31.143,121.805", timezone: "Asia/Chongqing")
Airport.create(code: "SFO", name: "San Francisco", city: "San Francisco", country: "United States", latlon: "37.619,-122.375", timezone: "America/Los_Angeles")
Airport.create(code: "TAB", name: "Tobago", city: "Scarborough", country: "Trinidad and Tobago", latlon: "11.15,-60.832", timezone: "America/Port_of_Spain")
Airport.create(code: "UVF", name: "Saint Lucia", city: "Hewandorra", country: "Saint Lucia", latlon: "13.733,-60.953", timezone: "America/St_Lucia")
Airport.create(code: "NRT", name: "Tokyo - Narita", city: "Tokyo", country: "Japan", latlon: "35.765,140.386", timezone: "Asia/Tokyo")
Airport.create(code: "BOM", name: "Mumbai", city: "Mumbai", country: "India", latlon: "19.089,72.868", timezone: "Asia/Calcutta")


vs033= Flight.create(flight_number: "VS033", origin: "LGW", destination: "ANU")
vs034= Flight.create(flight_number: "VS034", origin: "ANU", destination: "LGW")
vs103= Flight.create(flight_number: "VS103", origin: "LHR", destination: "ATL")
vs104= Flight.create(flight_number: "VS104", origin: "ATL", destination: "LHR")
vs115= Flight.create(flight_number: "VS115", origin: "LHR", destination: "ATL")
vs116= Flight.create(flight_number: "VS116", origin: "ATL", destination: "LHR")
vs109= Flight.create(flight_number: "VS109", origin: "MAN", destination: "ATL")
vs110= Flight.create(flight_number: "VS110", origin: "ATL", destination: "MAN")
vs029= Flight.create(flight_number: "VS029", origin: "LGW", destination: "BGI")
vs030= Flight.create(flight_number: "VS030", origin: "BGI", destination: "LGW")
vs077= Flight.create(flight_number: "VS077", origin: "MAN", destination: "BGI")
vs078= Flight.create(flight_number: "VS078", origin: "BGI", destination: "MAN")
vs011= Flight.create(flight_number: "VS011", origin: "LHR", destination: "BOS")
vs012= Flight.create(flight_number: "VS012", origin: "BOS", destination: "LHR")
vs093= Flight.create(flight_number: "VS093", origin: "LGW", destination: "CUN")
vs094= Flight.create(flight_number: "VS094", origin: "CUN", destination: "LHR")
vs603= Flight.create(flight_number: "VS603", origin: "LHR", destination: "CPT")
vs604= Flight.create(flight_number: "VS604", origin: "CPT", destination: "LHR")
vs039= Flight.create(flight_number: "VS039", origin: "LHR", destination: "ORD")
vs040= Flight.create(flight_number: "VS040", origin: "ORD", destination: "LHR")
vs300= Flight.create(flight_number: "VS300", origin: "LHR", destination: "DEL")
vs301= Flight.create(flight_number: "VS301", origin: "DEL", destination: "LHR")
vs107= Flight.create(flight_number: "VS107", origin: "LHR", destination: "DTW")
vs108= Flight.create(flight_number: "VS108", origin: "DTW", destination: "LHR")
vs400= Flight.create(flight_number: "VS400", origin: "LHR", destination: "DXB")
vs401= Flight.create(flight_number: "VS401", origin: "DXB", destination: "LHR")
vs063= Flight.create(flight_number: "VS063", origin: "LGW", destination: "HAV")
vs064= Flight.create(flight_number: "VS064", origin: "HAV", destination: "LGW")
vs200= Flight.create(flight_number: "VS200", origin: "LHR", destination: "HKG")
vs201= Flight.create(flight_number: "VS201", origin: "HKG", destination: "LHR")
vs601= Flight.create(flight_number: "VS601", origin: "LHR", destination: "JNB")
vs602= Flight.create(flight_number: "VS602", origin: "JNB", destination: "LHR")
vs651= Flight.create(flight_number: "VS651", origin: "LHR", destination: "LOS")
vs652= Flight.create(flight_number: "VS652", origin: "LOS", destination: "LHR")
vs043= Flight.create(flight_number: "VS043", origin: "LGW", destination: "LAS")
vs044= Flight.create(flight_number: "VS044", origin: "LAS", destination: "LGW")
vs085= Flight.create(flight_number: "VS085", origin: "MAN", destination: "LAS")
vs086= Flight.create(flight_number: "VS086", origin: "LAS", destination: "MAN")
vs163= Flight.create(flight_number: "VS163", origin: "GLA", destination: "LAS")
vs164= Flight.create(flight_number: "VS164", origin: "LAS", destination: "GLA")
vs951= Flight.create(flight_number: "VS951", origin: "LGW", destination: "LAS")
vs952= Flight.create(flight_number: "VS952", origin: "LAS", destination: "LGW")
vs007= Flight.create(flight_number: "VS007", origin: "LHR", destination: "LAX")
vs008= Flight.create(flight_number: "VS008", origin: "LAX", destination: "LHR")
vs023= Flight.create(flight_number: "VS023", origin: "LHR", destination: "LAX")
vs024= Flight.create(flight_number: "VS024", origin: "LAX", destination: "LHR")
vs005= Flight.create(flight_number: "VS005", origin: "LHR", destination: "MIA")
vs006= Flight.create(flight_number: "VS006", origin: "MIA", destination: "LHR")
vs065= Flight.create(flight_number: "VS065", origin: "LGW", destination: "MBJ")
vs066= Flight.create(flight_number: "VS066", origin: "MBJ", destination: "LGW")
vs001= Flight.create(flight_number: "VS001", origin: "LHR", destination: "EWR")
vs002= Flight.create(flight_number: "VS002", origin: "EWR", destination: "LHR")
vs017= Flight.create(flight_number: "VS017", origin: "LHR", destination: "EWR")
vs018= Flight.create(flight_number: "VS018", origin: "EWR", destination: "LHR")
vs354= Flight.create(flight_number: "VS354", origin: "LHR", destination: "BOM")
vs355= Flight.create(flight_number: "VS355", origin: "BOM", destination: "LHR")
vs003= Flight.create(flight_number: "VS003", origin: "LHR", destination: "JFK")
vs004= Flight.create(flight_number: "VS004", origin: "JFK", destination: "LHR")
vs009= Flight.create(flight_number: "VS009", origin: "LHR", destination: "JFK")
vs010= Flight.create(flight_number: "VS010", origin: "JFK", destination: "LHR")
vs025= Flight.create(flight_number: "VS025", origin: "LHR", destination: "JFK")
vs026= Flight.create(flight_number: "VS026", origin: "JFK", destination: "LHR")
vs045= Flight.create(flight_number: "VS045", origin: "LHR", destination: "JFK")
vs046= Flight.create(flight_number: "VS046", origin: "JFK", destination: "LHR")
vs111= Flight.create(flight_number: "VS111", origin: "LHR", destination: "JFK")
vs112= Flight.create(flight_number: "VS112", origin: "JFK", destination: "LHR")
vs161= Flight.create(flight_number: "VS161", origin: "BFS", destination: "MCO")
vs162= Flight.create(flight_number: "VS162", origin: "MCO", destination: "BFS")
vs015= Flight.create(flight_number: "VS015", origin: "LGW", destination: "MCO")
vs016= Flight.create(flight_number: "VS016", origin: "MCO", destination: "LGW")
vs027= Flight.create(flight_number: "VS027", origin: "LGW", destination: "MCO")
vs028= Flight.create(flight_number: "VS028", origin: "MCO", destination: "LGW")
vs049= Flight.create(flight_number: "VS049", origin: "LGW", destination: "MCO")
vs050= Flight.create(flight_number: "VS050", origin: "MCO", destination: "LGW")
vs071= Flight.create(flight_number: "VS071", origin: "GLA", destination: "MCO")
vs072= Flight.create(flight_number: "VS072", origin: "MCO", destination: "GLA")
vs073= Flight.create(flight_number: "VS073", origin: "MAN", destination: "MCO")
vs074= Flight.create(flight_number: "VS074", origin: "MCO", destination: "MAN")
vs075= Flight.create(flight_number: "VS075", origin: "MAN", destination: "MCO")
vs076= Flight.create(flight_number: "VS076", origin: "MCO", destination: "MAN")
vs019= Flight.create(flight_number: "VS019", origin: "LHR", destination: "SFO")
vs020= Flight.create(flight_number: "VS020", origin: "SFO", destination: "LHR")
vs041= Flight.create(flight_number: "VS041", origin: "LHR", destination: "SFO")
vs042= Flight.create(flight_number: "VS042", origin: "SFO", destination: "LHR")
vs250= Flight.create(flight_number: "VS250", origin: "LHR", destination: "PVG")
vs251= Flight.create(flight_number: "VS251", origin: "PVG", destination: "LHR")
vs087A= Flight.create(flight_number: "VS087A", origin: "LGW", destination: "UVF")
vs087B= Flight.create(flight_number: "VS087B", origin: "UVF", destination: "ANU")
vs088A= Flight.create(flight_number: "VS088A", origin: "ANU", destination: "UVF")
vs088B= Flight.create(flight_number: "VS088B", origin: "UVF", destination: "LGW")
vs089A= Flight.create(flight_number: "VS089A", origin: "LGW", destination: "UVF")
vs089B= Flight.create(flight_number: "VS089B", origin: "UVF", destination: "GND")
vs090A= Flight.create(flight_number: "VS090A", origin: "GND", destination: "UVF")
vs090B= Flight.create(flight_number: "VS090B", origin: "UVF", destination: "LGW")
vs097A= Flight.create(flight_number: "VS097A", origin: "LGW", destination: "UVF")
vs097B= Flight.create(flight_number: "VS097B", origin: "UVF", destination: "TAB")
vs098A= Flight.create(flight_number: "VS098A", origin: "TAB", destination: "UVF")
vs098B= Flight.create(flight_number: "VS098B", origin: "UVF", destination: "LGW")
vs021= Flight.create(flight_number: "VS021", origin: "LHR", destination: "IAD")
vs022= Flight.create(flight_number: "VS022", origin: "IAD", destination: "LHR")


FlightSchedule.create(flight_number: "VS033", departure: "10:00", arrival: "13:45", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:TRUE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,4,3), end_date: Date.new(2015,10,24), ac_type: "A333")
FlightSchedule.create(flight_number: "VS034", departure: "16:40", arrival: "5:45", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:TRUE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,4,3), end_date: Date.new(2015,10,23), ac_type: "A333")
FlightSchedule.create(flight_number: "VS034", departure: "16:40", arrival: "4:45", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "A333")
FlightSchedule.create(flight_number: "VS103", departure: "9:30", arrival: "14:05", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,24), ac_type: "A333")
FlightSchedule.create(flight_number: "VS104", departure: "18:15", arrival: "7:40", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,23), ac_type: "A333")
FlightSchedule.create(flight_number: "VS104", departure: "18:15", arrival: "6:40", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "A333")
FlightSchedule.create(flight_number: "VS109", departure: "11:00", arrival: "15:00", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,24), ac_type: "A333")
FlightSchedule.create(flight_number: "VS110", departure: "19:05", arrival: "8:30", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,23), ac_type: "A333")
FlightSchedule.create(flight_number: "VS110", departure: "19:05", arrival: "7:30", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "A333")
FlightSchedule.create(flight_number: "VS029", departure: "10:40", arrival: "14:25", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,3,29), ac_type: "B744")
FlightSchedule.create(flight_number: "VS029", departure: "10:40", arrival: "14:30", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,3,30), end_date: Date.new(2015,10,24), ac_type: "A333")
FlightSchedule.create(flight_number: "VS029", departure: "10:40", arrival: "14:30", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,4,5), end_date: Date.new(2015,10,18), ac_type: "A333")
FlightSchedule.create(flight_number: "VS030", departure: "16:55", arrival: "6:00", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,3,29), ac_type: "B744")
FlightSchedule.create(flight_number: "VS030", departure: "17:10", arrival: "6:40", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,3,30), end_date: Date.new(2015,10,23), ac_type: "A333")
FlightSchedule.create(flight_number: "VS030", departure: "17:10", arrival: "6:40", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,4,5), end_date: Date.new(2015,10,18), ac_type: "A333")
FlightSchedule.create(flight_number: "VS030", departure: "17:10", arrival: "5:40", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "A333")
FlightSchedule.create(flight_number: "VS077", departure: "13:45", arrival: "17:25", monday: TRUE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,3,30), end_date: Date.new(2015,10,19), ac_type: "B744")
FlightSchedule.create(flight_number: "VS078", departure: "19:55", arrival: "9:00", monday: TRUE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,3,30), end_date: Date.new(2015,10,19), ac_type: "B744")
FlightSchedule.create(flight_number: "VS011", departure: "17:30", arrival: "19:50", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,4,9), ac_type: "A343")
FlightSchedule.create(flight_number: "VS011", departure: "17:30", arrival: "19:50", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:TRUE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,4,10), end_date: Date.new(2015,5,9), ac_type: "A333")
FlightSchedule.create(flight_number: "VS011", departure: "17:30", arrival: "19:50", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,4,12), end_date: Date.new(2015,5,14), ac_type: "A343")
FlightSchedule.create(flight_number: "VS011", departure: "17:30", arrival: "19:50", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,5,15), end_date: Date.new(2015,10,24), ac_type: "A343")
FlightSchedule.create(flight_number: "VS012", departure: "21:50", arrival: "9:10", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,4,9), ac_type: "A343")
FlightSchedule.create(flight_number: "VS012", departure: "21:50", arrival: "9:10", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:TRUE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,4,10), end_date: Date.new(2015,5,9), ac_type: "A333")
FlightSchedule.create(flight_number: "VS012", departure: "21:50", arrival: "9:10", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,4,12), end_date: Date.new(2015,5,14), ac_type: "A343")
FlightSchedule.create(flight_number: "VS012", departure: "21:50", arrival: "9:10", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,5,15), end_date: Date.new(2015,10,23), ac_type: "A343")
FlightSchedule.create(flight_number: "VS012", departure: "21:50", arrival: "8:10", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "A343")
FlightSchedule.create(flight_number: "VS093", departure: "12:20", arrival: "15:30", monday: FALSE, tuesday: TRUE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,3,31), end_date: Date.new(2015,4,4), ac_type: "B744")
FlightSchedule.create(flight_number: "VS093", departure: "12:20", arrival: "16:30", monday: FALSE, tuesday: TRUE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,4,7), end_date: Date.new(2015,10,24), ac_type: "B744")
FlightSchedule.create(flight_number: "VS094", departure: "17:55", arrival: "10:10", monday: FALSE, tuesday: TRUE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,3,31), end_date: Date.new(2015,4,4), ac_type: "B744")
FlightSchedule.create(flight_number: "VS094", departure: "18:55", arrival: "10:10", monday: FALSE, tuesday: TRUE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,4,7), end_date: Date.new(2015,10,22), ac_type: "B744")
FlightSchedule.create(flight_number: "VS094", departure: "18:55", arrival: "9:10", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "B744")
FlightSchedule.create(flight_number: "VS603", departure: "18:50", arrival: "7:55", monday: FALSE, tuesday: FALSE, wednesday: TRUE, thursday:FALSE, friday:TRUE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,4,26), ac_type: "A346")
FlightSchedule.create(flight_number: "VS604", departure: "21:20", arrival: "8:40", monday: TRUE, tuesday: FALSE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,4,4), ac_type: "A346")
FlightSchedule.create(flight_number: "VS604", departure: "21:20", arrival: "8:40", monday: TRUE, tuesday: FALSE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,4,6), end_date: Date.new(2015,4,27), ac_type: "A346")
FlightSchedule.create(flight_number: "VS039", departure: "11:35", arrival: "14:10", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,4,29), end_date: Date.new(2015,10,19), ac_type: "A333")
FlightSchedule.create(flight_number: "VS040", departure: "18:40", arrival: "8:40", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,4,29), end_date: Date.new(2015,10,19), ac_type: "A333")
FlightSchedule.create(flight_number: "VS300", departure: "22:00", arrival: "10:40", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,24), ac_type: "B789")
FlightSchedule.create(flight_number: "VS301", departure: "13:45", arrival: "18:45", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,3,29), ac_type: "A333")
FlightSchedule.create(flight_number: "VS301", departure: "13:25", arrival: "17:55", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,30), end_date: Date.new(2015,10,24), ac_type: "B789")
FlightSchedule.create(flight_number: "VS107", departure: "9:30", arrival: "12:35", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,6,1), end_date: Date.new(2015,10,24), ac_type: "A333")
FlightSchedule.create(flight_number: "VS108", departure: "19:25", arrival: "7:05", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,6,1), end_date: Date.new(2015,10,23), ac_type: "A333")
FlightSchedule.create(flight_number: "VS108", departure: "19:25", arrival: "6:05", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "A333")
FlightSchedule.create(flight_number: "VS400", departure: "22:00", arrival: "8:00", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,24), ac_type: "A333")
FlightSchedule.create(flight_number: "VS401", departure: "11:10", arrival: "15:55", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,24), ac_type: "A333")
FlightSchedule.create(flight_number: "VS063", departure: "12:15", arrival: "17:00", monday: TRUE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,3,30), end_date: Date.new(2015,10,19), ac_type: "B744")
FlightSchedule.create(flight_number: "VS063", departure: "11:30", arrival: "16:15", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,4,2), end_date: Date.new(2015,10,22), ac_type: "B744")
FlightSchedule.create(flight_number: "VS064", departure: "19:30", arrival: "9:15", monday: TRUE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,3,30), end_date: Date.new(2015,10,19), ac_type: "B744")
FlightSchedule.create(flight_number: "VS064", departure: "19:05", arrival: "8:50", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,4,2), end_date: Date.new(2015,10,22), ac_type: "B744")
FlightSchedule.create(flight_number: "VS200", departure: "22:30", arrival: "17:50", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,24), ac_type: "A346")
FlightSchedule.create(flight_number: "VS201", departure: "23:25", arrival: "5:25", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,23), ac_type: "A346")
FlightSchedule.create(flight_number: "VS201", departure: "23:25", arrival: "4:25", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "A346")
FlightSchedule.create(flight_number: "VS601", departure: "21:00", arrival: "9:05", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,7,14), ac_type: "A346")
FlightSchedule.create(flight_number: "VS601", departure: "21:00", arrival: "9:05", monday: FALSE, tuesday: FALSE, wednesday: TRUE, thursday:FALSE, friday:TRUE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,7,15), end_date: Date.new(2015,10,23), ac_type: "A343")
FlightSchedule.create(flight_number: "VS601", departure: "21:00", arrival: "9:05", monday: TRUE, tuesday: TRUE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,7,16), end_date: Date.new(2015,10,24), ac_type: "A346")
FlightSchedule.create(flight_number: "VS602", departure: "20:10", arrival: "6:35", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,7,15), ac_type: "A346")
FlightSchedule.create(flight_number: "VS602", departure: "20:10", arrival: "6:35", monday: TRUE, tuesday: FALSE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,7,16), end_date: Date.new(2015,10,22), ac_type: "A343")
FlightSchedule.create(flight_number: "VS602", departure: "20:10", arrival: "6:35", monday: FALSE, tuesday: TRUE, wednesday: TRUE, thursday:FALSE, friday:TRUE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,7,17), end_date: Date.new(2015,10,23), ac_type: "A346")
FlightSchedule.create(flight_number: "VS602", departure: "20:10", arrival: "5:35", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "A343")
FlightSchedule.create(flight_number: "VS651", departure: "22:20", arrival: "5:25", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,24), ac_type: "A346")
FlightSchedule.create(flight_number: "VS652", departure: "10:05", arrival: "16:50", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,24), ac_type: "A346")
FlightSchedule.create(flight_number: "VS043", departure: "11:20", arrival: "14:05", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,24), ac_type: "B744")
FlightSchedule.create(flight_number: "VS044", departure: "16:35", arrival: "10:25", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,23), ac_type: "B744")
FlightSchedule.create(flight_number: "VS044", departure: "16:35", arrival: "9:25", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "B744")
FlightSchedule.create(flight_number: "VS085", departure: "12:35", arrival: "14:55", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,22), ac_type: "B744")
FlightSchedule.create(flight_number: "VS086", departure: "17:30", arrival: "11:05", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,22), ac_type: "B744")
FlightSchedule.create(flight_number: "VS163", departure: "10:00", arrival: "11:55", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,9,10), end_date: Date.new(2015,10,1), ac_type: "B744")
FlightSchedule.create(flight_number: "VS164", departure: "14:25", arrival: "7:55", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,9,17), end_date: Date.new(2015,10,8), ac_type: "B744")
FlightSchedule.create(flight_number: "VS951", departure: "9:10", arrival: "11:55", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,10,8), end_date: Date.new(2015,10,8), ac_type: "B744")
FlightSchedule.create(flight_number: "VS952", departure: "14:10", arrival: "8:00", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,9,10), end_date: Date.new(2015,9,10), ac_type: "B744")
FlightSchedule.create(flight_number: "VS007", departure: "11:15", arrival: "14:35", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,4,3), ac_type: "A346")
FlightSchedule.create(flight_number: "VS007", departure: "11:15", arrival: "14:35", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,4,4), end_date: Date.new(2015,5,7), ac_type: "B744")
FlightSchedule.create(flight_number: "VS007", departure: "11:15", arrival: "14:35", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,5,8), end_date: Date.new(2015,6,1), ac_type: "A346")
FlightSchedule.create(flight_number: "VS007", departure: "11:15", arrival: "14:35", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,6,2), end_date: Date.new(2015,8,14), ac_type: "B744")
FlightSchedule.create(flight_number: "VS007", departure: "11:15", arrival: "14:35", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,8,15), end_date: Date.new(2015,10,24), ac_type: "A346")
FlightSchedule.create(flight_number: "VS008", departure: "17:01", arrival: "11:30", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,4,3), ac_type: "A346")
FlightSchedule.create(flight_number: "VS008", departure: "17:01", arrival: "11:30", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,4,4), end_date: Date.new(2015,5,7), ac_type: "B744")
FlightSchedule.create(flight_number: "VS008", departure: "17:01", arrival: "11:30", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,5,8), end_date: Date.new(2015,6,1), ac_type: "A346")
FlightSchedule.create(flight_number: "VS008", departure: "17:01", arrival: "11:30", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,6,2), end_date: Date.new(2015,8,14), ac_type: "B744")
FlightSchedule.create(flight_number: "VS008", departure: "17:01", arrival: "11:30", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,8,15), end_date: Date.new(2015,10,23), ac_type: "A346")
FlightSchedule.create(flight_number: "VS008", departure: "17:01", arrival: "10:30", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "A346")
FlightSchedule.create(flight_number: "VS023", departure: "12:35", arrival: "16:05", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,24), ac_type: "A346")
FlightSchedule.create(flight_number: "VS024", departure: "22:20", arrival: "16:50", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,23), ac_type: "A346")
FlightSchedule.create(flight_number: "VS024", departure: "22:20", arrival: "15:50", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "A346")
FlightSchedule.create(flight_number: "VS005", departure: "12:30", arrival: "17:00", monday: TRUE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,24), ac_type: "B744")
FlightSchedule.create(flight_number: "VS005", departure: "12:30", arrival: "17:00", monday: FALSE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,3,31), end_date: Date.new(2015,9,3), ac_type: "A333")
FlightSchedule.create(flight_number: "VS005", departure: "12:30", arrival: "17:00", monday: FALSE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,9,8), end_date: Date.new(2015,9,17), ac_type: "A346")
FlightSchedule.create(flight_number: "VS005", departure: "12:30", arrival: "17:00", monday: FALSE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,9,22), end_date: Date.new(2015,10,22), ac_type: "A333")
FlightSchedule.create(flight_number: "VS006", departure: "20:50", arrival: "10:30", monday: TRUE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,23), ac_type: "B744")
FlightSchedule.create(flight_number: "VS006", departure: "20:50", arrival: "10:30", monday: FALSE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,3,31), end_date: Date.new(2015,9,3), ac_type: "A333")
FlightSchedule.create(flight_number: "VS006", departure: "20:50", arrival: "10:30", monday: FALSE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,9,8), end_date: Date.new(2015,9,17), ac_type: "A346")
FlightSchedule.create(flight_number: "VS006", departure: "20:50", arrival: "10:30", monday: FALSE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,9,22), end_date: Date.new(2015,10,22), ac_type: "A333")
FlightSchedule.create(flight_number: "VS006", departure: "20:50", arrival: "10:30", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "B744")
FlightSchedule.create(flight_number: "VS065", departure: "12:40", arrival: "16:15", monday: FALSE, tuesday: FALSE, wednesday: TRUE, thursday:FALSE, friday:TRUE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,23), ac_type: "B744")
FlightSchedule.create(flight_number: "VS066", departure: "18:45", arrival: "9:45", monday: FALSE, tuesday: FALSE, wednesday: TRUE, thursday:FALSE, friday:TRUE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,23), ac_type: "B744")
FlightSchedule.create(flight_number: "VS001", departure: "17:10", arrival: "19:55", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,5,21), ac_type: "B789")
FlightSchedule.create(flight_number: "VS001", departure: "17:10", arrival: "19:55", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:TRUE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,4,3), end_date: Date.new(2015,4,25), ac_type: "A333")
FlightSchedule.create(flight_number: "VS001", departure: "17:10", arrival: "19:55", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:TRUE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,5,1), end_date: Date.new(2015,5,16), ac_type: "A346")
FlightSchedule.create(flight_number: "VS001", departure: "17:10", arrival: "19:55", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,5,22), end_date: Date.new(2015,6,18), ac_type: "B789")
FlightSchedule.create(flight_number: "VS001", departure: "17:10", arrival: "19:55", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:TRUE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,6,19), end_date: Date.new(2015,7,11), ac_type: "A346")
FlightSchedule.create(flight_number: "VS001", departure: "17:10", arrival: "19:55", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,6,21), end_date: Date.new(2015,7,16), ac_type: "B789")
FlightSchedule.create(flight_number: "VS001", departure: "17:10", arrival: "19:55", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,7,17), end_date: Date.new(2015,8,14), ac_type: "B789")
FlightSchedule.create(flight_number: "VS001", departure: "17:10", arrival: "19:55", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:TRUE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,8,15), end_date: Date.new(2015,10,24), ac_type: "A346")
FlightSchedule.create(flight_number: "VS001", departure: "17:10", arrival: "19:55", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,8,16), end_date: Date.new(2015,10,22), ac_type: "B789")
FlightSchedule.create(flight_number: "VS002", departure: "22:30", arrival: "10:30", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,5,21), ac_type: "B789")
FlightSchedule.create(flight_number: "VS002", departure: "22:30", arrival: "10:30", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:TRUE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,4,3), end_date: Date.new(2015,4,25), ac_type: "A333")
FlightSchedule.create(flight_number: "VS002", departure: "22:30", arrival: "10:30", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:TRUE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,5,1), end_date: Date.new(2015,5,16), ac_type: "A346")
FlightSchedule.create(flight_number: "VS002", departure: "22:30", arrival: "10:30", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,5,22), end_date: Date.new(2015,6,18), ac_type: "B789")
FlightSchedule.create(flight_number: "VS002", departure: "22:30", arrival: "10:30", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:TRUE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,6,19), end_date: Date.new(2015,7,11), ac_type: "A346")
FlightSchedule.create(flight_number: "VS002", departure: "22:30", arrival: "10:30", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,6,21), end_date: Date.new(2015,7,16), ac_type: "B789")
FlightSchedule.create(flight_number: "VS002", departure: "22:30", arrival: "10:30", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,7,17), end_date: Date.new(2015,8,14), ac_type: "B789")
FlightSchedule.create(flight_number: "VS002", departure: "22:30", arrival: "10:30", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:TRUE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,8,15), end_date: Date.new(2015,10,23), ac_type: "A346")
FlightSchedule.create(flight_number: "VS002", departure: "22:30", arrival: "10:30", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,8,16), end_date: Date.new(2015,10,22), ac_type: "B789")
FlightSchedule.create(flight_number: "VS002", departure: "22:30", arrival: "9:30", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "A346")
FlightSchedule.create(flight_number: "VS018", departure: "8:00", arrival: "20:00", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,3,29), ac_type: "A333")
FlightSchedule.create(flight_number: "VS003", departure: "9:05", arrival: "11:40", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,24), ac_type: "A343")
FlightSchedule.create(flight_number: "VS004", departure: "18:30", arrival: "6:30", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,23), ac_type: "A343")
FlightSchedule.create(flight_number: "VS004", departure: "18:30", arrival: "5:30", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "A343")
FlightSchedule.create(flight_number: "VS009", departure: "16:15", arrival: "19:05", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,24), ac_type: "B744")
FlightSchedule.create(flight_number: "VS010", departure: "21:30", arrival: "9:25", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,23), ac_type: "B744")
FlightSchedule.create(flight_number: "VS010", departure: "21:30", arrival: "8:25", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "B744")
FlightSchedule.create(flight_number: "VS025", departure: "20:05", arrival: "23:00", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,24), ac_type: "A333")
FlightSchedule.create(flight_number: "VS026", departure: "7:40", arrival: "19:40", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,24), ac_type: "A333")
FlightSchedule.create(flight_number: "VS045", departure: "14:00", arrival: "16:40", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,24), ac_type: "B744")
FlightSchedule.create(flight_number: "VS046", departure: "19:30", arrival: "8:00", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,23), ac_type: "B744")
FlightSchedule.create(flight_number: "VS046", departure: "19:30", arrival: "7:00", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "B744")
FlightSchedule.create(flight_number: "VS111", departure: "12:30", arrival: "15:10", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,24), ac_type: "A333")
FlightSchedule.create(flight_number: "VS112", departure: "20:35", arrival: "8:15", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,23), ac_type: "A333")
FlightSchedule.create(flight_number: "VS112", departure: "20:35", arrival: "7:15", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "A333")
FlightSchedule.create(flight_number: "VS161", departure: "12:35", arrival: "16:05", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,6,25), end_date: Date.new(2015,7,16), ac_type: "B744")
FlightSchedule.create(flight_number: "VS162", departure: "18:35", arrival: "7:25", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,7,9), end_date: Date.new(2015,7,30), ac_type: "B744")
FlightSchedule.create(flight_number: "VS015", departure: "13:00", arrival: "17:10", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,24), ac_type: "B744")
FlightSchedule.create(flight_number: "VS016", departure: "19:35", arrival: "8:45", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,23), ac_type: "B744")
FlightSchedule.create(flight_number: "VS016", departure: "19:35", arrival: "7:45", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "B744")
FlightSchedule.create(flight_number: "VS027", departure: "11:15", arrival: "15:25", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,4,15), ac_type: "B744")
FlightSchedule.create(flight_number: "VS027", departure: "11:15", arrival: "15:25", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:FALSE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,4,17), end_date: Date.new(2015,7,22), ac_type: "B744")
FlightSchedule.create(flight_number: "VS027", departure: "11:15", arrival: "15:25", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,7,23), end_date: Date.new(2015,9,6), ac_type: "B744")
FlightSchedule.create(flight_number: "VS027", departure: "11:15", arrival: "15:25", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:FALSE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,10,6), end_date: Date.new(2015,10,24), ac_type: "B744")
FlightSchedule.create(flight_number: "VS028", departure: "18:15", arrival: "7:25", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,4,15), ac_type: "B744")
FlightSchedule.create(flight_number: "VS028", departure: "18:15", arrival: "7:25", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:FALSE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,4,17), end_date: Date.new(2015,6,24), ac_type: "B744")
FlightSchedule.create(flight_number: "VS028", departure: "18:15", arrival: "7:25", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,6,25), end_date: Date.new(2015,7,2), ac_type: "B744")
FlightSchedule.create(flight_number: "VS028", departure: "18:15", arrival: "7:25", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:FALSE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,7,3), end_date: Date.new(2015,7,29), ac_type: "B744")
FlightSchedule.create(flight_number: "VS028", departure: "18:15", arrival: "7:25", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,7,30), end_date: Date.new(2015,9,13), ac_type: "B744")
FlightSchedule.create(flight_number: "VS028", departure: "18:15", arrival: "7:25", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:FALSE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,10,6), end_date: Date.new(2015,10,24), ac_type: "B744")
FlightSchedule.create(flight_number: "VS028", departure: "18:15", arrival: "8:25", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "B744")
FlightSchedule.create(flight_number: "VS049", departure: "9:45", arrival: "14:10", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,7,26), end_date: Date.new(2015,8,30), ac_type: "B744")
FlightSchedule.create(flight_number: "VS050", departure: "17:15", arrival: "6:05", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,8,9), end_date: Date.new(2015,8,30), ac_type: "B744")
FlightSchedule.create(flight_number: "VS071", departure: "12:05", arrival: "15:40", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:TRUE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,4,3), end_date: Date.new(2015,10,23), ac_type: "B744")
FlightSchedule.create(flight_number: "VS071", departure: "10:05", arrival: "13:40", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,4,4), end_date: Date.new(2015,10,24), ac_type: "B744")
FlightSchedule.create(flight_number: "VS071", departure: "10:05", arrival: "13:40", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,6,28), end_date: Date.new(2015,7,19), ac_type: "B744")
FlightSchedule.create(flight_number: "VS071", departure: "10:05", arrival: "13:40", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,9,13), end_date: Date.new(2015,10,4), ac_type: "B744")
FlightSchedule.create(flight_number: "VS072", departure: "18:25", arrival: "7:15", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:TRUE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,4,3), end_date: Date.new(2015,10,23), ac_type: "B744")
FlightSchedule.create(flight_number: "VS072", departure: "16:25", arrival: "5:15", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,4,4), end_date: Date.new(2015,10,17), ac_type: "B744")
FlightSchedule.create(flight_number: "VS072", departure: "16:25", arrival: "5:15", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,7,12), end_date: Date.new(2015,8,2), ac_type: "B744")
FlightSchedule.create(flight_number: "VS072", departure: "16:25", arrival: "5:15", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,9,20), end_date: Date.new(2015,10,4), ac_type: "B744")
FlightSchedule.create(flight_number: "VS072", departure: "17:25", arrival: "6:15", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,10,11), end_date: Date.new(2015,10,18), ac_type: "B744")
FlightSchedule.create(flight_number: "VS072", departure: "16:25", arrival: "4:15", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "B744")
FlightSchedule.create(flight_number: "VS073", departure: "13:45", arrival: "17:45", monday: FALSE, tuesday: TRUE, wednesday: TRUE, thursday:FALSE, friday:TRUE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,3,31), end_date: Date.new(2015,10,24), ac_type: "B744")
FlightSchedule.create(flight_number: "VS074", departure: "20:25", arrival: "9:30", monday: FALSE, tuesday: TRUE, wednesday: TRUE, thursday:FALSE, friday:TRUE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,3,31), end_date: Date.new(2015,10,23), ac_type: "B744")
FlightSchedule.create(flight_number: "VS074", departure: "20:25", arrival: "8:30", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "B744")
FlightSchedule.create(flight_number: "VS075", departure: "11:00", arrival: "15:00", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,24), ac_type: "B744")
FlightSchedule.create(flight_number: "VS076", departure: "18:55", arrival: "8:00", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,23), ac_type: "B744")
FlightSchedule.create(flight_number: "VS076", departure: "18:55", arrival: "7:00", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "B744")
FlightSchedule.create(flight_number: "VS019", departure: "13:00", arrival: "16:00", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,24), ac_type: "B744")
FlightSchedule.create(flight_number: "VS020", departure: "18:50", arrival: "13:05", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,22), ac_type: "B744")
FlightSchedule.create(flight_number: "VS020", departure: "19:45", arrival: "14:00", monday: TRUE, tuesday: TRUE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,3,30), end_date: Date.new(2015,10,20), ac_type: "B744")
FlightSchedule.create(flight_number: "VS020", departure: "18:15", arrival: "12:30", monday: FALSE, tuesday: FALSE, wednesday: TRUE, thursday:FALSE, friday:TRUE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,4,1), end_date: Date.new(2015,10,23), ac_type: "B744")
FlightSchedule.create(flight_number: "VS020", departure: "19:45", arrival: "13:00", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "B744")
FlightSchedule.create(flight_number: "VS041", departure: "15:45", arrival: "19:05", monday: FALSE, tuesday: TRUE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,20), ac_type: "A346")
FlightSchedule.create(flight_number: "VS041", departure: "14:50", arrival: "18:10", monday: FALSE, tuesday: FALSE, wednesday: TRUE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,4,1), end_date: Date.new(2015,10,14), ac_type: "A346")
FlightSchedule.create(flight_number: "VS041", departure: "15:35", arrival: "18:55", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,4,2), end_date: Date.new(2015,10,17), ac_type: "A346")
FlightSchedule.create(flight_number: "VS042", departure: "22:50", arrival: "17:20", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,18), ac_type: "A346")
FlightSchedule.create(flight_number: "VS042", departure: "22:15", arrival: "16:45", monday: FALSE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,3,31), end_date: Date.new(2015,10,20), ac_type: "A346")
FlightSchedule.create(flight_number: "VS250", departure: "15:15", arrival: "9:40", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,6,14), ac_type: "A346")
FlightSchedule.create(flight_number: "VS250", departure: "15:15", arrival: "9:40", monday: TRUE, tuesday: FALSE, wednesday: TRUE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,6,15), end_date: Date.new(2015,7,13), ac_type: "A343")
FlightSchedule.create(flight_number: "VS250", departure: "15:15", arrival: "9:40", monday: FALSE, tuesday: TRUE, wednesday: FALSE, thursday:TRUE, friday:TRUE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,6,16), end_date: Date.new(2015,7,14), ac_type: "A346")
FlightSchedule.create(flight_number: "VS250", departure: "15:15", arrival: "9:40", monday: FALSE, tuesday: FALSE, wednesday: TRUE, thursday:FALSE, friday:TRUE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,7,15), end_date: Date.new(2015,10,23), ac_type: "A346")
FlightSchedule.create(flight_number: "VS250", departure: "15:15", arrival: "9:40", monday: TRUE, tuesday: TRUE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,7,16), end_date: Date.new(2015,10,24), ac_type: "A343")
FlightSchedule.create(flight_number: "VS251", departure: "11:40", arrival: "17:20", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,6,15), ac_type: "A346")
FlightSchedule.create(flight_number: "VS251", departure: "11:40", arrival: "17:20", monday: FALSE, tuesday: TRUE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,6,16), end_date: Date.new(2015,7,14), ac_type: "A343")
FlightSchedule.create(flight_number: "VS251", departure: "11:40", arrival: "17:20", monday: TRUE, tuesday: FALSE, wednesday: TRUE, thursday:FALSE, friday:TRUE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,6,17), end_date: Date.new(2015,7,15), ac_type: "A346")
FlightSchedule.create(flight_number: "VS251", departure: "11:40", arrival: "17:20", monday: TRUE, tuesday: FALSE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,7,16), end_date: Date.new(2015,10,24), ac_type: "A346")
FlightSchedule.create(flight_number: "VS251", departure: "11:40", arrival: "17:20", monday: FALSE, tuesday: TRUE, wednesday: TRUE, thursday:FALSE, friday:TRUE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,7,17), end_date: Date.new(2015,10,23), ac_type: "A343")
FlightSchedule.create(flight_number: "VS087A", departure: "9:00", arrival: "12:55", monday: FALSE, tuesday: TRUE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,3,31), end_date: Date.new(2015,10,20), ac_type: "A333")
FlightSchedule.create(flight_number: "VS087B", departure: "13:55", arrival: "14:55", monday: FALSE, tuesday: TRUE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,3,31), end_date: Date.new(2015,10,20), ac_type: "A333")
FlightSchedule.create(flight_number: "VS088A", departure: "16:55", arrival: "17:55", monday: FALSE, tuesday: TRUE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,3,31), end_date: Date.new(2015,10,20), ac_type: "A333")
FlightSchedule.create(flight_number: "VS088B", departure: "18:55", arrival: "8:25", monday: FALSE, tuesday: TRUE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,3,31), end_date: Date.new(2015,10,20), ac_type: "A333")
FlightSchedule.create(flight_number: "VS089A", departure: "9:00", arrival: "12:55", monday: TRUE, tuesday: FALSE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,3,30), end_date: Date.new(2015,10,22), ac_type: "A333")
FlightSchedule.create(flight_number: "VS089B", departure: "13:55", arrival: "14:55", monday: TRUE, tuesday: FALSE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,3,30), end_date: Date.new(2015,10,22), ac_type: "A333")
FlightSchedule.create(flight_number: "VS090A", departure: "16:55", arrival: "17:55", monday: TRUE, tuesday: FALSE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,3,30), end_date: Date.new(2015,10,22), ac_type: "A333")
FlightSchedule.create(flight_number: "VS090B", departure: "18:55", arrival: "8:25", monday: TRUE, tuesday: FALSE, wednesday: FALSE, thursday:TRUE, friday:FALSE, saturday:FALSE, sunday:FALSE, start_date: Date.new(2015,3,30), end_date: Date.new(2015,10,22), ac_type: "A333")
FlightSchedule.create(flight_number: "VS097A", departure: "9:00", arrival: "12:55", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,18), ac_type: "A333")
FlightSchedule.create(flight_number: "VS097B", departure: "13:55", arrival: "14:50", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,18), ac_type: "A333")
FlightSchedule.create(flight_number: "VS098A", departure: "16:40", arrival: "17:35", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,18), ac_type: "A333")
FlightSchedule.create(flight_number: "VS098B", departure: "18:55", arrival: "8:25", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,10,18), ac_type: "A333")
FlightSchedule.create(flight_number: "VS021", departure: "11:00", arrival: "14:15", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,9,11), ac_type: "A333")
FlightSchedule.create(flight_number: "VS021", departure: "11:00", arrival: "14:15", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,9,12), end_date: Date.new(2015,9,16), ac_type: "A346")
FlightSchedule.create(flight_number: "VS021", departure: "11:00", arrival: "14:15", monday: FALSE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,9,17), end_date: Date.new(2015,9,26), ac_type: "A333")
FlightSchedule.create(flight_number: "VS021", departure: "11:00", arrival: "14:15", monday: TRUE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,9,20), end_date: Date.new(2015,9,21), ac_type: "A346")
FlightSchedule.create(flight_number: "VS021", departure: "11:00", arrival: "14:15", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,9,27), end_date: Date.new(2015,10,24), ac_type: "A333")
FlightSchedule.create(flight_number: "VS022", departure: "18:40", arrival: "7:05", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,3,29), end_date: Date.new(2015,9,11), ac_type: "A333")
FlightSchedule.create(flight_number: "VS022", departure: "18:40", arrival: "7:05", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,9,12), end_date: Date.new(2015,9,16), ac_type: "A346")
FlightSchedule.create(flight_number: "VS022", departure: "18:40", arrival: "7:05", monday: FALSE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,9,17), end_date: Date.new(2015,9,26), ac_type: "A333")
FlightSchedule.create(flight_number: "VS022", departure: "18:40", arrival: "7:05", monday: TRUE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:FALSE, sunday:TRUE, start_date: Date.new(2015,9,20), end_date: Date.new(2015,9,21), ac_type: "A346")
FlightSchedule.create(flight_number: "VS022", departure: "18:40", arrival: "7:05", monday: TRUE, tuesday: TRUE, wednesday: TRUE, thursday:TRUE, friday:TRUE, saturday:TRUE, sunday:TRUE, start_date: Date.new(2015,9,27), end_date: Date.new(2015,10,23), ac_type: "A333")
FlightSchedule.create(flight_number: "VS022", departure: "18:40", arrival: "6:05", monday: FALSE, tuesday: FALSE, wednesday: FALSE, thursday:FALSE, friday:FALSE, saturday:TRUE, sunday:FALSE, start_date: Date.new(2015,10,24), end_date: Date.new(2015,10,24), ac_type: "A333")